### ISSUE TITLE
The "Harvested into" section of harvestable plant infoboxes links to the wrong page.

### ISSUE THREAD

**Issue by pokedragonboy** [syntaxaire/qud-wiki#12]
Basically, the infobox capitalizes all the words in a title, while pages only capitalize the first.
For example, Vantabloom links to "Vanta Petals" not "Vanta petals", and thus the link does not go anywhere.

**Comment by Wreckstation** [comment]
Fixed in 99ff398, updated all the plants I could find that would be affected by this
