### ISSUE TITLE
QBE returns [[No results (cooking effect)|No results]] for all preserved foods.

### ISSUE THREAD

**Issue by pokedragonboy** [syntaxaire/qud-wiki#17]
This is perhaps an issue with {{CookEffect ID to name}}, as QBE correctly displays the cooking effect in QBE itself.

For example, spine fruit jam has "| cookeffect = {{CookEffect ID to name|reflect}}" in the template it exports to the wiki, but the cooking effect still shows up as "no results" on the actual wiki.

**Comment by Wreckstation** [comment]
Not the fault of QBE, because all cooking effects aren't on the wiki right now. I did update the query to return the regular argument if nothing was found so its more readable. Will be fixing this later today
