### ISSUE TITLE
Tiles of creatures with the part "HologramMaterial"/"HologramWallMaterial" do not have their hologram color

### ISSUE THREAD

**Issue by Wreckstation** [syntaxaire/qud-wiki#18]
Hologram colors are defined in cs and flicker often, but I think there should at least be an attempt, say to replace the detail color with C and tile color to b. I tried to implement this myself but realized qud tile had no reference to the object and took everything from the init, making it more complicated than I thought. 

Thing this affects: Wraith-Knights (although must specifically check for this bc the hologram part is added in code), holographic ivory, holographic beth, Hologram Distraction,  hologram of shekinah, HoloMarble

**Comment by egocarib** [comment]
The majority of the time, holographic entities (with the `HologramMaterial` part) use the colors `B` and `b`, or specifically:
```cs
pRender.ColorString = "&B";
pRender.TileColor = "&B";
pRender.DetailColor = "b";
```
