### ISSUE TITLE
Tier Doesn't Factor in Mods - Should It?

### ISSUE THREAD

**Issue by egocarib** [syntaxaire/qud-wiki#23]
A good example is the [Sparbine](https://cavesofqud.gamepedia.com/Scoped_masterwork_carbine). QBE lists this as Tier 4, which is technically correct. However, for the purposes of adding additional mods, it has an *effective* tinkering level of 6, because it already has two mods, and the tinkering screen treats it as a Tier 6 item.

I'm not sure if Tier has meaning anywhere else in the game - I confirmed that the game code doesn't actually increase the Tier when you mod something, it just adds Tier + Number_of_Mods when the Tinkering Screen is open to determine which bits you need to use for adding an additional mod.

So I guess my question is:
* Should we continue to list items with their "base" Tier, or should we show the *effective* Tier instead?

**Comment by Wreckstation** [comment]
I'd go for effective tier because checking each tier type with QBE right now is impossible. or add a + to the right of the tier to indicate it can be greater if moddable?

**Comment by egocarib** [comment]
I like the idea of doing a `+`. So the (Sparbine)[https://cavesofqud.gamepedia.com/Scoped_masterwork_carbine] would show a Tier of `4+2`, similar to how the mutation levels look with an ego boost right now.

What's the best way to make that happen? Do we need to add a new QBE parameter for `modcount` or something like that, so the wiki knows how many mods are already on the item? Or is there another way we can figure that out?

**Comment by Wreckstation** [comment]
i think modcount would be a good idea (or set up a counter in the `mods` iterator and make that a self parameter)
