### ISSUE TITLE
PVPowered Not Applicable for All Vibro Weapons

### ISSUE THREAD

**Issue by egocarib** [syntaxaire/qud-wiki#26]
https://github.com/syntaxaire/qud-wiki/blob/772634b195edd1061ca3e1328026e04bb9daac2d/qudobject.py#L1070

Right now this causes every [vibro weapon](https://cavesofqud.gamepedia.com/Vibro_weapons) to show `PV (unpowered): 4/4` on the wiki, but I don't think that's accurate.

**Comment by Wreckstation** [comment]
Is it? Even a vibrokhopesh is EMP sensitive and will default to 4 damage.

**Comment by egocarib** [comment]
I was thinking stuff like "small stone" and the natural weapons that are also in that category. I don't have the XML in front of me now though, so I wasn't able to confirm how those work myself.
