### ISSUE TITLE
Repeated part types overwrite previous ones

### ISSUE THREAD

**Issue by Wreckstation** [syntaxaire/qud-wiki#3]
Things such as inventory Blueprint="" or mutation Name="", skill Name="" in creatures will only have one of each type of these show up in the property list

**Comment by syntaxaire** [comment]
Working on this next, also, this is a test comment for the Discord webhook.

**Comment by syntaxaire** [comment]
I believe this was actually fixed by 5056209d2b8d46cdeea9d560902e7baf5512de10.
