### ISSUE TITLE
refactor qudobject.py

### ISSUE THREAD

**Issue by egocarib** [syntaxaire/qud-wiki#34]
`qudobject` has gotten too long and we should refactor it (as @syntaxaire previously pointed out).

I'm not 100% sure the best way to refactor, being less experienced with python. Some internet searches seem to suggest there are multiple ways to handle splitting up a class across more than one file (making the class inherit from other classes, import methods into the class, create subclasses, etc.) and I'm not sure which method should be preferred.

Thematically we could likely split `qudobject` into smaller modules such as `qudobject_character`, `qudobject_weapon`/`qudobject_item`, or similar.

**Comment by syntaxaire** [comment]
Closed with the QudObject - QudObjectProps - QudObjectWiki class hierarchy and the splitting of QudObject and QudObjectProps into a Python package.
