### ISSUE TITLE
QBE does not create tiles with the color (124, 101, 44, 255)

### ISSUE THREAD

**Issue by pokedragonboy** [syntaxaire/qud-wiki#6]
A long list of the tiles affected can be found by simply running the command to open QBE in your terminal.

**Comment by pokedragonboy** [comment]
A long list of the tiles affected can be found by simply running the command to open QBE in your terminal.

**Comment by Wreckstation** [comment]
The issue with these colors is that Qud does some esoteric fomula with colors that are not pure black/white (see: https://cavesofqud.gamepedia.com/Modding:_Tiles#Tile_Format for what tiles look like unprocessed). You can see this in game in Great Saltbacks (https://cavesofqud.gamepedia.com/File:Great_saltback.png) and Spray bottles which use different color tiles and result in colors outside of the normal color pallet. We have to fully understand what qud does to create these colors before QBE is able to render these tiles

**Comment by syntaxaire** [comment]
Still looking into how these colours are rendered. For now I'm disabling the extra debug output for these tiles, since we can turn it back on for debugging when needed.

**Comment by Wreckstation** [comment]
Fixed with commit [https://github.com/syntaxaire/qud-wiki/commit/2157bae36d7a5ce725cfbf1b1d443f3937d7f763](url)
