### ISSUE TITLE
Auto-generated creature descriptions on the wiki have =article= included in them.

### ISSUE THREAD

**Issue by pokedragonboy** [syntaxaire/qud-wiki#7]
Currently, this seems to be affecting:
Glow-Wight Cultist of Agolgut
Glow-Wight Shepherd of Agolgut
Cannibal
Svenlainard

Additionally, in my brief look through the creatures in QBE, it seems that these 4 are the only ones who have =article= included in the descriptions QBE outputs for them.

**Comment by HeladoDeBrownie** [comment]
i can confirm that that variable appears that way in the game data. the real problem is that it isn't substituted for a value before displaying it in the creatures' articles

**Comment by Wreckstation** [comment]
all =grammar= processing is done directly on the wiki, not QBE. But i'm the one in charge of that so i'll mark it as closed when i fix it anyway

**Comment by Wreckstation** [comment]
Should work now [https://cavesofqud.gamepedia.com/Svenlainard](url)
